### PR TITLE
added currency symbol and commas, fixed bug 

### PR DESCRIPTION
**Pull request by patrickkee**
I needed this for a project i'm working on so I enhanced it. You won't hurt my feelings if you reject the pull request of course, but I think it's a positive enhancement.

### CODE REVIEW

**Comment by ianmcnally** [comment]
Hey Patrick, thanks for sending your work along. Can you contextualize the changes for me – both the how and why?

**Comment by patrickkee** [comment]
Hey, I see I need to clean up my syntax a bunch so I'll do that tomorrow. 

I write up a very descriptive comment but github wouldn't let me post it so I'll try again tomorrow...I'm on mobile now which seems to work.

**Comment by patrickkee** [comment]
Ian,
I needed a currency masked input for my project and I found your repo. After using it a bit I wanted the option of having the currency mask include a currency symbol, commas, and no decimal places (for larger numbers). For example:

Original format: 1000000.02
New format: $1,000,000.02
Alt new format: $1,000,000

I implemented this by adding two new props to the component - "showCents" which is a boolean for toggling them on and off, and "currencySymbol" which takes anything the user gives like $ to be concatenated to the front of the number.

Along the way of implementing this I found two bugs (the second bug may have been something I introduced, not sure on that one). The first bug was that if I passed a number in I got an error when we tried to call the regex .mask() function on it. I fixed that by casting the input as a string in the constructor and in componentWIllRecieveProps. 

The next bug I found was that if the value i passed in was formatted as 20.3 it would be rendered as 2.03 because the array join method didn't know that there was a missing zero on the end. I resolved this by implementing the normalizeToFixed() method which I call in both the constructor and in the componentWillRecieve props. 

Finally, I cleaned up as much of the eslint output as I could, though it's complaining about react's use of "this" in this.setstate, so I can't really fix that bit.

**Comment by patrickkee** [comment]
Hey, I'll fix the failing unit tests tonight

**Pull request closed without merging**
